openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'
info:
  title: Todo API
  description: Todo API
  version: 1.0.0
  contact:
    email: kevin@sakemaer.fr
  license:
    name: MIT
    url: 'https://gitlab.com/sakemaer/shelf_helpers/-/blob/main/LICENSE'
tags:
  - name: healthcheck
  - name: todos
paths:
  /:
    get:
      tags:
        - healthcheck
      summary: Health check
      description: |
        Health check to see if server is up and available.
      operationId: healthCheck
      responses:
        '200':
          description: server is up
  /todos:
    get:
      tags:
        - todos
      summary: List the available tasks
      description: |
        The list of tasks can be filtered by their status.
      operationId: listTodos
      parameters:
        - name: status
          in: query
          description: Filters the tasks by their status
          required: false
          schema:
            type: string
            enum:
              - done
              - waiting
              - working
              - all
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
            application/xml:
              schema:
                $ref: '#/components/schemas/TodoList'
        '400':
          description: Invalid status value
    post:
      tags:
        - todos
      summary: Create a todo
      description: 'create a todo'
      operationId: createTodo
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
            application/xml:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodo'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateTodo'
          application/x-www-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Todo'
    delete:
      tags:
        - todos
      operationId: deleteAllTodo
      description: 'delete all todo from database'
      security:
        - BasicAuth: []
        - BearerAuth: []
        - ApiKeyAuth: []
      responses:
        '200':
          description: 'delete all todo'

  '/todos/{todoId}':
    put:
      tags:
        - todos
      summary: Update the todo
      description: |
        Update the todo title and status
      operationId: updateTodo
      parameters:
        - name: todoId
          in: path
          description: The todo identifier
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
            application/xml:
              schema:
                $ref: '#/components/schemas/Todo'

        '400':
          description: |
           Invalid input
        '404':
          description: |
            The todo does not exist.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodo'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateTodo'
          application/x-www-urlencoded:
            schema:
              $ref: '#/components/schemas/UpdateTodo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateTodo'

    delete:
      tags:
        - todos
      summary: Delete the todo
      description: |
        Delete the todo
      operationId: deleteTodo
      parameters:
        - name: todoId
          in: path
          description: The todo identifier
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: |
            No content.
        '404':
          description: |
            The todo does not exist.
security: []
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie

  schemas:
    TodoList:
      type: array
      items:
        $ref: '#/components/schemas/Todo'
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: false
          description: The todo identifier
        title:
          type: string
          nullable: false
          description: The todo title
        createDate:
          type: string
          nullable: false
          format: date-time
          description: The todo creation date
        doneDate:
          type: string
          format: date-time
          description: The todo resolution date
        status:
          type: string
          nullable: false
          description: The todo state
          enum:
            - waiting
            - working
            - done
      required:
        - id
        - title
        - status
        - createDate
      example:
        id: 23
        title: Make the FOSDEM presentation
        status: working
        createDate: '2017-12-24T00:00:00.000Z'
    CreateTodo:
      type: object
      title: CreateTodo
      properties:
        title:
          description: The todo title
          type: string
          minLength: 5
          example: This is my first todo
      required:
        - title
    UpdateTodo:
      type: object
      title: UpdateTodo
      required:
        - title
        - status
      properties:
        title:
          description: The todo title
          type: string
          minLength: 5
        status:
          description: The todo status
          type: string
          enum:
            - working
            - waiting
            - done