name: shelf_helpers_example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_helpers: 
    path: ../
  shelf_hotreload: ^1.4.0
  shelf_router: ^1.1.3
  sqlite3: ^1.11.0
  xml: ^6.2.2


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
