name: shelf_helpers
description: Some helpers to ease the use of shelf
version: 1.0.0-alpha.3
# homepage: https://www.example.com

repository: https://gitlab.com/sakemaer/shelf_helpers
issue_tracker: https://gitlab.com/sakemaer/shelf_helpers/-/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.1.1
  meta: ^1.9.1
  mime: ^1.0.4
  shelf: ^1.4.0
  shelf_multipart: ^1.0.0
  xml: ^6.2.2
  xml2json: ^5.3.6

dev_dependencies:
  lints: ^2.0.0
  shelf_router: ^1.1.3
  test: ^1.16.0

