name: top_shelf
description: Some helpers to ease the use of shelf
version: 1.0.0-alpha.9
# homepage: https://www.example.com

repository: https://github.com/sakemaer/top_shelf
issue_tracker: https://gitlab.com/sakemaer/shelf_helpers/-/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  clock: ^1.1.1
  crypto: ^3.0.3
  fake_async: ^1.3.1
  logging: ^1.1.1
  meta: ^1.9.1
  mime: ^1.0.4
  pointycastle: ^3.9.1  
  quiver: ^3.2.1
  shelf: ^1.4.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.3
  sqlite3: ^2.4.3 
  xml: ^6.2.2
  xml2json: ^6.2.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0

