name: shelf_helpers
description: Some helpers to ease the use of shelf
version: 0.9.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  shelf: ^1.4.0
  xml2json: ^5.3.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  xml: ^6.2.2

